# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0002_auto_20170502_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrado',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='myfolder/'),
        ),
    ]
